package com.rakuriku.rakuriku.domain.model.compe;
// Generated Jan 16, 2022, 2:40:17 PM by Hibernate Tools 5.3.9.Final


import com.rakuriku.rakuriku.domain.model.BaseEntity;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * EntriesEntity generated by hbm2java
 */
@Entity
@Table(name="entries"
    ,schema="public"
)
public class EntriesEntity extends BaseEntity implements java.io.Serializable {


     private String id;
     private String name;
     private String nameKana;
     private String sex;
     private String phoneNumber;
     private String number;
     private Integer totalParticipationFee;
     private Set<CompeEntryManagementEntity> compeEntryManagements = new HashSet<CompeEntryManagementEntity>(0);

    public EntriesEntity() {
    }

	
    public EntriesEntity(String id, String name, String nameKana, String sex, String phoneNumber) {
        this.id = id;
        this.name = name;
        this.nameKana = nameKana;
        this.sex = sex;
        this.phoneNumber = phoneNumber;
    }
    public EntriesEntity(String id, String name, String nameKana, String sex, String phoneNumber, String number, Integer totalParticipationFee, Set<CompeEntryManagementEntity> compeEntryManagements) {
       this.id = id;
       this.name = name;
       this.nameKana = nameKana;
       this.sex = sex;
       this.phoneNumber = phoneNumber;
       this.number = number;
       this.totalParticipationFee = totalParticipationFee;
       this.compeEntryManagements = compeEntryManagements;
    }
   
     @Id 

    
    @Column(name="id", unique=true, nullable=false, length=36)
    public String getId() {
        return this.id;
    }
    
    public void setId(String id) {
        this.id = id;
    }

    
    @Column(name="name", nullable=false)
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }

    
    @Column(name="name_kana", nullable=false)
    public String getNameKana() {
        return this.nameKana;
    }
    
    public void setNameKana(String nameKana) {
        this.nameKana = nameKana;
    }

    
    @Column(name="sex", nullable=false, length=1)
    public String getSex() {
        return this.sex;
    }
    
    public void setSex(String sex) {
        this.sex = sex;
    }

    
    @Column(name="phone_number", nullable=false, length=30)
    public String getPhoneNumber() {
        return this.phoneNumber;
    }
    
    public void setPhoneNumber(String phoneNumber) {
        this.phoneNumber = phoneNumber;
    }

    
    @Column(name="number", length=10)
    public String getNumber() {
        return this.number;
    }
    
    public void setNumber(String number) {
        this.number = number;
    }

    
    @Column(name="total_participation_fee")
    public Integer getTotalParticipationFee() {
        return this.totalParticipationFee;
    }
    
    public void setTotalParticipationFee(Integer totalParticipationFee) {
        this.totalParticipationFee = totalParticipationFee;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="entries")
    public Set<CompeEntryManagementEntity> getCompeEntryManagements() {
        return this.compeEntryManagements;
    }
    
    public void setCompeEntryManagements(Set<CompeEntryManagementEntity> compeEntryManagements) {
        this.compeEntryManagements = compeEntryManagements;
    }




}


