package com.rakuriku.rakuriku.entities.auth;
// Generated Sep 23, 2021, 2:42:56 PM by Hibernate Tools 5.3.9.Final


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

import com.rakuriku.rakuriku.entities.BaseEntity;

/**
 * AdminsEntity generated by hbm2java
 */
@Entity
@Table(name="admins"
    ,schema="public"
)
public class AdminsEntity extends BaseEntity implements java.io.Serializable {


     private String userId;
     private String password;
     private String emailAddress;
     private String role;

    public AdminsEntity() {
    }

    public AdminsEntity(String userId, String password, String emailAddress, String role) {
       this.userId = userId;
       this.password = password;
       this.emailAddress = emailAddress;
       this.role = role;
    }
   
     @Id 

    
    @Column(name="user_id", unique=true, nullable=false)
    public String getUserId() {
        return this.userId;
    }
    
    public void setUserId(String userId) {
        this.userId = userId;
    }

    
    @Column(name="password", nullable=false)
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }

    
    @Column(name="email_address", nullable=false)
    public String getEmailAddress() {
        return this.emailAddress;
    }
    
    public void setEmailAddress(String emailAddress) {
        this.emailAddress = emailAddress;
    }

    
    @Column(name="role", nullable=false, length=100)
    public String getRole() {
        return this.role;
    }
    
    public void setRole(String role) {
        this.role = role;
    }




}


