package com.rakuriku.rakuriku.entities.compe;
// Generated Nov 3, 2021, 7:07:13 AM by Hibernate Tools 5.3.9.Final


import com.rakuriku.rakuriku.entities.auth.AdminsEntity;
import io.sitoolkit.dba.infra.jpa.BaseEntity;
import java.io.Serializable;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * CompeEntity generated by hbm2java
 */
@Entity
@Table(name="compe"
    ,schema="public"
)
@TypeDefs({
    @TypeDef(name = "jsonb", typeClass = JsonBinaryType.class)
})
public class CompeEntity extends BaseEntity implements java.io.Serializable {


     private String compeId;
     private AdminsEntity admins;
     private String compeName;
     private String compeDates;
     private String compePlace;
     private byte[] compeGuidelinesFile;
     private Serializable compeEvent;

    public CompeEntity() {
    }

	
    public CompeEntity(String compeId, AdminsEntity admins, String compeName, String compeDates, String compePlace, Serializable compeEvent) {
        this.compeId = compeId;
        this.admins = admins;
        this.compeName = compeName;
        this.compeDates = compeDates;
        this.compePlace = compePlace;
        this.compeEvent = compeEvent;
    }
    public CompeEntity(String compeId, AdminsEntity admins, String compeName, String compeDates, String compePlace, byte[] compeGuidelinesFile, Serializable compeEvent) {
       this.compeId = compeId;
       this.admins = admins;
       this.compeName = compeName;
       this.compeDates = compeDates;
       this.compePlace = compePlace;
       this.compeGuidelinesFile = compeGuidelinesFile;
       this.compeEvent = compeEvent;
    }
   
     @Id 

    
    @Column(name="compe_id", unique=true, nullable=false)
    public String getCompeId() {
        return this.compeId;
    }
    
    public void setCompeId(String compeId) {
        this.compeId = compeId;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="admin_id", nullable=false)
    public AdminsEntity getAdmins() {
        return this.admins;
    }
    
    public void setAdmins(AdminsEntity admins) {
        this.admins = admins;
    }

    
    @Column(name="compe_name", nullable=false)
    public String getCompeName() {
        return this.compeName;
    }
    
    public void setCompeName(String compeName) {
        this.compeName = compeName;
    }

    
    @Column(name="compe_dates", nullable=false, length=100)
    public String getCompeDates() {
        return this.compeDates;
    }
    
    public void setCompeDates(String compeDates) {
        this.compeDates = compeDates;
    }

    
    @Column(name="compe_place", nullable=false, length=100)
    public String getCompePlace() {
        return this.compePlace;
    }
    
    public void setCompePlace(String compePlace) {
        this.compePlace = compePlace;
    }

    
    @Column(name="compe_guidelines_file")
    public byte[] getCompeGuidelinesFile() {
        return this.compeGuidelinesFile;
    }
    
    public void setCompeGuidelinesFile(byte[] compeGuidelinesFile) {
        this.compeGuidelinesFile = compeGuidelinesFile;
    }

    @Type(type = "jsonb")
    @Column(name="compe_event", nullable=false, columnDefinition = "jsonb")
    public Serializable getCompeEvent() {
        return this.compeEvent;
    }
    
    public void setCompeEvent(Serializable compeEvent) {
        this.compeEvent = compeEvent;
    }




}


