package com.rakuriku.rakuriku.domain.model.auth;
// Generated Dec 5, 2021, 2:23:52 PM by Hibernate Tools 5.3.9.Final


import com.rakuriku.rakuriku.domain.model.BaseEntity;
import com.rakuriku.rakuriku.domain.model.compe.CompeEntity;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * AdminsEntity generated by hbm2java
 */
@Entity
@Table(name="admins"
    ,schema="public"
)
public class AdminsEntity extends BaseEntity implements java.io.Serializable {


     private String adminId;
     private String password;
     private String emailAddress;
     private String role;
     private Set<CompeEntity> compes = new HashSet<CompeEntity>(0);

    public AdminsEntity() {
    }

	
    public AdminsEntity(String adminId, String password, String emailAddress, String role) {
        this.adminId = adminId;
        this.password = password;
        this.emailAddress = emailAddress;
        this.role = role;
    }
    public AdminsEntity(String adminId, String password, String emailAddress, String role, Set<CompeEntity> compes) {
       this.adminId = adminId;
       this.password = password;
       this.emailAddress = emailAddress;
       this.role = role;
       this.compes = compes;
    }
   
     @Id 

    
    @Column(name="admin_id", unique=true, nullable=false)
    public String getAdminId() {
        return this.adminId;
    }
    
    public void setAdminId(String adminId) {
        this.adminId = adminId;
    }

    
    @Column(name="password", nullable=false)
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }

    
    @Column(name="email_address", nullable=false)
    public String getEmailAddress() {
        return this.emailAddress;
    }
    
    public void setEmailAddress(String emailAddress) {
        this.emailAddress = emailAddress;
    }

    
    @Column(name="role", nullable=false, length=100)
    public String getRole() {
        return this.role;
    }
    
    public void setRole(String role) {
        this.role = role;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="admins")
    public Set<CompeEntity> getCompes() {
        return this.compes;
    }
    
    public void setCompes(Set<CompeEntity> compes) {
        this.compes = compes;
    }




}


